version: '3.7'
services:
 postgres:
  image: postgres:12.0-alpine
  container_name: siiip-postgres
  working_dir: /data/postgres
  volumes:
   - ./postgresql-data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: siiip
   POSTGRES_PASSWORD: des.siiip.2020!
   POSTGRES_DB: siiip

 php:
  image: 'php:7-apache'
  container_name: siiip-php
  build: .
  volumes:
   - './www/:/var/www/html'
  expose:
   - 80
  ports:
   - '80:80'
  links:
   - postgres
