name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  strategy:
    matrix:
      python-version: [3.8]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - name: Build the stack
        run: docker-compose up -d
      - name: Build e2e stack
        run: sudo docker-compose -f tests/docker-compose.yml up -d
      - name: Download python
        run: pip -r tests/requirements.txt
      - name: e2e
        run: behave tests/features